apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: oumaima778/fastapi-app:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always  # Ajout de la politique de pull de l'image
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
      nodePort: 30163
  type: NodePort
