# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app/fastapi

# Copy the FastAPI application files into the container
COPY . /app/fastapi

# Install any needed packages  for FastAPI
RUN pip install --no-cache-dir fastapi uvicorn scikit-learn pillow opencv-python-headless

# Expose port 8000 for FastAPI
EXPOSE 8000

# Run FastAPI app when the container launches
CMD ["python", "FastApi.py"] 