# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /fastapi/app

# Copy the current directory contents into the container at /app
COPY . /fastapi/app

# Install any needed packages 
RUN pip install --no-cache-dir fastapi uvicorn scikit-learn pillow opencv-python-headless

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV PYTHONUNBUFFERED=1

# Run app.py when the container launches
CMD ["python", "FastApi.py"] 