apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
      - name: flaskapi-container
        image: oumaima778/flaskapi-app:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always  # Ajout de la politique de pull de l'image
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapi-service
spec:
  selector:
    app: flaskapi
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
      nodePort: 30164
  type: NodePort
