# Utiliser une image Python officielle comme base
FROM python:3.9-slim

# Définir le répertoire de travail à l'intérieur du conteneur
WORKDIR /app/flaskapi

# Copier les fichiers de l'application vers le répertoire de travail du conteneur
COPY . /app/flaskapi

# Installer les dépendances pour Flask
RUN pip install --no-cache-dir flask requests

# Exposer le port 5000 pour accéder à l'API Flask
EXPOSE 5000

# Définir la commande par défaut pour exécuter l'application Flask
CMD ["python", "test.py"]
